Fix line number reporting
cucumber-rs/gherkin pull request #33
Opened 2022-02-16 11:11 UTC by ilslv

## Synopsis

Currently reported line number may be greater that the actual one. This happens, because `GherkinEnv::line_offsets` may contain duplicates.

## Solution

Check whether value already exists before pushing into `GherkinEnv::line_offsets`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-02-16 11:12 UTC, ilslv commented
```
Fix parsed line number (#33)
```

2022-02-16 13:39 UTC, tyranron requested changes
@ilslv could you also add similar tests for comments? Thanks.

2022-02-16 13:39 UTC, tyranron commented on CHANGELOG.md
> +- Fix line number reporting ([#33])
That's for `### Fixed` section.

2022-02-18 09:40 UTC, tyranron approved these changes
@ilslv thanks!

2022-02-18 09:46 UTC, merged